apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: elasticsearches.example.cloudflight.io
spec:
  group: example.cloudflight.io
  names:
    kind: ElasticSearch
    listKind: ElasticSearchList
    plural: elasticsearches
    singular: elasticsearch
  scope: Namespaced
  subresources:
    status: {}
  versions:
  - name: v1alpha1
    served: true
    storage: true
