---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ meta.name }}"
  namespace: "{{ meta.namespace }}"
  labels:
    app:
      "{{ meta.name }}"
data:
  elasticsearch.yml: |-
    cluster.name: {{ cluster_name }}
    discovery.zen:
      ping.unicast.hosts:
      - {{ meta.name }} 
    node.name: ${HOSTNAME}
    cluster.initial_master_nodes: ['{{meta.name}}-0']
    network.host: 0.0.0.0
