---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  labels:
    app: "{{ meta.name }}"
  name: "{{ meta.name }}"
  namespace: "{{ meta.namespace }}"
spec:
  clusterIP: None
  ports:
    - name: transport
      port: 9300
      protocol: TCP
      targetPort: 9300
    - name: http
      port: 9200
      protocol: TCP
      targetPort: 9200
  selector:
    app: "{{ meta.name }}"
  type: ClusterIP
